import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import {
  Outlet,
    Link,
      createRootRouteWithContext,
        useRouter,
          HeadContent,
            Scripts,
            } from "@tanstack/react-router";
            import { useEffect, type ReactNode } from "react";

            import appCss from "../styles.css?url";
            import { reportLovableError } from "../lib/lovable-error-reporting";
            import { BookingBar } from "../components/site/booking-bar";
            import { SiteHeader } from "../components/site/header";
            import { SiteFooter } from "../components/site/footer";
            import { WhatsAppButton } from "../components/site/whatsapp-button";

            function NotFoundComponent() {
              return (
                  <div className="flex min-h-screen items-center justify-center bg-background px-4">
                        <div className="max-w-md text-center">
                                <h1 className="text-7xl font-serif text-foreground">404</h1>
                                        <h2 className="mt-4 text-xl font-semibold text-foreground">Page not found</h2>
                                                <p className="mt-2 text-sm text-muted-foreground">
                                                          The page you're looking for doesn't exist or has been moved.
                                                                  </p>
                                                                          <div className="mt-6">
                                                                                    <Link
                                                                                                to="/"
                                                                                                            className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
                                                                                                                      >
                                                                                                                                  Go home
                                                                                                                                            </Link>
                                                                                                                                                    </div>
                                                                                                                                                          </div>
                                                                                                                                                              </div>
                                                                                                                                                                );
                                                                                                                                                                }

                                                                                                                                                                function ErrorComponent({ error, reset }: { error: Error; reset: () => void }) {
                                                                                                                                                                  console.error(error);
                                                                                                                                                                    const router = useRouter();
                                                                                                                                                                      useEffect(() => {
                                                                                                                                                                          reportLovableError(error, { boundary: "tanstack_root_error_component" });
                                                                                                                                                                            }, [error]);

                                                                                                                                                                              return (
                                                                                                                                                                                  <div className="flex min-h-screen items-center justify-center bg-background px-4">
                                                                                                                                                                                        <div className="max-w-md text-center">
                                                                                                                                                                                                <h1 className="text-xl font-semibold tracking-tight text-foreground">
                                                                                                                                                                                                          This page didn't load
                                                                                                                                                                                                                  </h1>
                                                                                                                                                                                                                          <p className="mt-2 text-sm text-muted-foreground">
                                                                                                                                                                                                                                    Something went wrong on our end. You can try refreshing or head back home.
                                                                                                                                                                                                                                            </p>
                                                                                                                                                                                                                                                    <div className="mt-6 flex flex-wrap justify-center gap-2">
                                                                                                                                                                                                                                                              <button
                                                                                                                                                                                                                                                                          onClick={() => {
                                                                                                                                                                                                                                                                                        router.invalidate();
                                                                                                                                                                                                                                                                                                      reset();
                                                                                                                                                                                                                                                                                                                  }}
                                                                                                                                                                                                                                                                                                                              className="inline-flex items-center justify-center rounded-md bg-primary px-4 py-2 text-sm font-medium text-primary-foreground transition-colors hover:bg-primary/90"
                                                                                                                                                                                                                                                                                                                                        >
                                                                                                                                                                                                                                                                                                                                                    Try again
                                                                                                                                                                                                                                                                                                                                                              </button>
                                                                                                                                                                                                                                                                                                                                                                        <a
                                                                                                                                                                                                                                                                                                                                                                                    href="/"
                                                                                                                                                                                                                                                                                                                                                                                                className="inline-flex items-center justify-center rounded-md border border-input bg-background px-4 py-2 text-sm font-medium text-foreground transition-colors hover:bg-accent"
                                                                                                                                                                                                                                                                                                                                                                                                          >
                                                                                                                                                                                                                                                                                                                                                                                                                      Go home
                                                                                                                                                                                                                                                                                                                                                                                                                                </a>
                                                                                                                                                                                                                                                                                                                                                                                                                                        </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                              </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                  </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                    );
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                    export const Route = createRootRouteWithContext<{ queryClient: QueryClient }>()({
                                                                                                                                                                                                                                                                                                                                                                                                                                                      head: () => ({
                                                                                                                                                                                                                                                                                                                                                                                                                                                          meta: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                { charSet: "utf-8" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { name: "viewport", content: "width=device-width, initial-scale=1" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { title: "Lakshmi Oral & Dental Care | Trusted Dental Clinic in HSR Layout & Kudlu, Bengaluru" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          name: "description",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  content:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          "Lakshmi Oral & Dental Care provides expert Root Canal Treatment, Cosmetic Dentistry, Dental Implants, Braces, Teeth Whitening, Pediatric Dentistry, and complete family dental care. Visit our clinics in HSR Layout and Kudlu, Bengaluru. Book your appointment online."  ,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: "keywords",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        content:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "dentist HSR Layout, dentist Kudlu, dental clinic HSR Layout, dental clinic Kudlu, root canal specialist Bengaluru, cosmetic dentist Bengaluru, dental implants HSR Layout, dental implants Kudlu, Lakshmi Oral & Dental Care",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { name: "author", content: "Lakshmi Oral And Dental Care" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              { property: "og:title", content: "Lakshmi Oral & Dental Care | HSR Layout & Kudlu, Bengaluru" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            property: "og:description",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    content:
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                               "Trusted dental care in Bengaluru with two convenient locations in HSR Layout and Kudlu. Expert Root Canal, Cosmetic Dentistry, Dental Implants, Braces, Teeth Whitening, and family dental care.",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { property: "og:type", content: "website" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        name: "theme-color",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                content: "#0F766E",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            { name: "twitter:card", content: "summary_large_image" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    links: [
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          { rel: "stylesheet", href: appCss },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                { rel: "preconnect", href: "https://fonts.googleapis.com" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      { rel: "preconnect", href: "https://fonts.gstatic.com", crossOrigin: "anonymous" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    rel: "stylesheet",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            href: "https://fonts.googleapis.com/css2?family=Fraunces:wght@400;500;600;700&family=Inter:wght@400;500;600;700&display=swap",
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        { rel: "icon", href: "/favicon.png", type: "image/x-icon" },
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            ],
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              }),
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                shellComponent: RootShell,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  component: RootComponent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    notFoundComponent: NotFoundComponent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      errorComponent: ErrorComponent,
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      function RootShell({ children }: { children: ReactNode }) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            <html lang="en">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <HeadContent />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </head>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              {children}
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      <Scripts />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            </body>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </html>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  function RootComponent() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    const { queryClient } = Route.useRouteContext();

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      return (
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <QueryClientProvider client={queryClient}>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <div className="flex min-h-screen flex-col">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <BookingBar />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                <SiteHeader />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        <main className="flex-1">
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <Outlet />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          </main>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  <SiteFooter />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                          <WhatsAppButton />
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                </div>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    </QueryClientProvider>
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      );
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                      